import type { Event } from "@/components/EventsTab";

export const eventsData: Event[] = [
  {
    id: "commit-or-rollback",
    title: "COMMIT or ROLLBACK",
    organizer: "DBMS Domain Team",
    shortDescription: "DBMS fundamentals and query problem-solving challenge.",
    fullDescription:
      "A two-round technical event testing conceptual DBMS clarity and practical query skills. Round 1 covers RA expressions, normalization, transactions, indexing, and NoSQL. Round 2 focuses on scenario-based query solving and output accuracy.",
    eventDate: "2026-03-09T09:30:00",
    duration: "2h 5m",
    mode: "Offline",
    category: "tech",
    rating: 4.6,
    reviewCount: 128,
    registrations: 340,
    tags: ["DBMS", "Queries", "SQL"],
    thumbnailImage: "/file.svg",
    bannerImage: "/window.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-25",
    capacity: 420,
    seatsRemaining: 80,
    difficultyLevel: "Intermediate",
    certificateProvided: true,
    price: "Free",
    sponsors: ["Data Circle"],
    location: "Lab Block A",
    trendingScore: 86,
    featured: true,
  },
  {
    id: "build-the-brain",
    title: "BUILD THE BRAIN",
    organizer: "AI/ML Track",
    shortDescription: "AI reasoning + LLM agent development event.",
    fullDescription:
      "Round 1 is a clue-based logical deduction sprint with limited yes/no questions. Round 2 is a hands-on LLM agent build from a given problem statement, judged on requirement fulfillment, output quality, and optimization.",
    eventDate: "2026-03-09T11:00:00",
    duration: "2h 30m",
    mode: "Hybrid",
    category: "tech",
    rating: 4.8,
    reviewCount: 152,
    registrations: 410,
    tags: ["AI", "LLM", "Agent"],
    thumbnailImage: "/next.svg",
    bannerImage: "/globe.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-25",
    capacity: 500,
    seatsRemaining: 90,
    difficultyLevel: "Advanced",
    certificateProvided: true,
    price: "$10",
    sponsors: ["ML Forge"],
    location: "Innovation Lab + Online",
    trendingScore: 93,
    featured: true,
  },
  {
    id: "runtime",
    title: "RUNTIME",
    organizer: "Coding Arena",
    shortDescription: "Error identification and pressure debugging challenge.",
    fullDescription:
      "A two-round debugging event. Round 1 asks teams to identify exact error types from code snippets. Round 2 provides buggy code with constraints and teamwork coordination challenges, with winners determined by correct output and completion order.",
    eventDate: "2026-03-09T14:00:00",
    duration: "1h 50m",
    mode: "Offline",
    category: "tech",
    rating: 4.5,
    reviewCount: 97,
    registrations: 290,
    tags: ["Debugging", "Programming", "Logic"],
    thumbnailImage: "/vercel.svg",
    bannerImage: "/file.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-24",
    capacity: 360,
    seatsRemaining: 70,
    difficultyLevel: "Intermediate",
    certificateProvided: true,
    price: "Free",
    sponsors: ["Code Sprint"],
    location: "Systems Lab 2",
    trendingScore: 79,
    featured: false,
  },
  {
    id: "techodu-vilaiyadu",
    title: "Techodu Vilaiyadu",
    organizer: "Puzzle & Quiz Cell",
    shortDescription: "Tech clues, riddles, and taboo-style word guessing.",
    fullDescription:
      "Round 1 includes one-line clues, images, riddles, and logic puzzles with tech answers. Round 2 is a fast-paced tech word guessing format where teams score by clarity, creativity, and correct guesses under time limits.",
    eventDate: "2026-03-10T09:30:00",
    duration: "1h 30m",
    mode: "Offline",
    category: "tech",
    rating: 4.4,
    reviewCount: 84,
    registrations: 250,
    tags: ["Puzzle", "Quiz", "Team"],
    thumbnailImage: "/window.svg",
    bannerImage: "/next.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-24",
    capacity: 320,
    seatsRemaining: 70,
    difficultyLevel: "Beginner",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Tech Club"],
    location: "Seminar Hall C",
    trendingScore: 74,
    featured: false,
  },
  {
    id: "security-arena",
    title: "Security Arena",
    organizer: "Cyber Security Team",
    shortDescription: "Cybersecurity quiz + digital investigation challenge.",
    fullDescription:
      "Round 1 is an online security screening quiz with Linux, crypto, and security fundamentals. Round 2 is a crime-thriller investigation where teams analyze evidence, decode hidden clues, and derive final conclusions.",
    eventDate: "2026-03-10T09:30:00",
    duration: "5h",
    mode: "Hybrid",
    category: "tech",
    rating: 4.9,
    reviewCount: 174,
    registrations: 390,
    tags: ["Cybersecurity", "Linux", "Investigation"],
    thumbnailImage: "/globe.svg",
    bannerImage: "/vercel.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-25",
    capacity: 450,
    seatsRemaining: 60,
    difficultyLevel: "Advanced",
    certificateProvided: true,
    price: "$15",
    sponsors: ["SecureOps"],
    location: "Cyber Lab + Online Portal",
    trendingScore: 95,
    featured: true,
  },
  {
    id: "project-presentation-day",
    title: "Project Presentation - Day",
    organizer: "Innovation Showcase",
    shortDescription: "Real-world software/IoT solution presentation event.",
    fullDescription:
      "Teams submit project drafts in Round 1 and present shortlisted ideas to judges in Round 2. Focus areas include innovation, feasibility, architecture, implementation approach, impact, and scalability.",
    eventDate: "2026-03-10T09:30:00",
    duration: "3h 30m",
    mode: "Offline",
    category: "workshops",
    rating: 4.7,
    reviewCount: 111,
    registrations: 260,
    tags: ["Project", "Presentation", "IoT"],
    thumbnailImage: "/file.svg",
    bannerImage: "/globe.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-23",
    capacity: 300,
    seatsRemaining: 40,
    difficultyLevel: "Intermediate",
    certificateProvided: true,
    price: "Free",
    sponsors: ["Campus Labs"],
    location: "Main Hall",
    trendingScore: 82,
    featured: true,
  },
  {
    id: "brainbid",
    title: "BRAINBID",
    organizer: "Reasoning Circuit",
    shortDescription: "Aptitude and reasoning auction-style quiz format.",
    fullDescription:
      "Teams bid for questions and answer under a scoring mechanism where correctness adds points and wrong answers deduct points. Final ranking depends on score and rapid-fire tie-breakers when needed.",
    eventDate: "2026-03-10T09:30:00",
    duration: "40m",
    mode: "Offline",
    category: "workshops",
    rating: 4.3,
    reviewCount: 76,
    registrations: 220,
    tags: ["Aptitude", "Bidding", "Reasoning"],
    thumbnailImage: "/window.svg",
    bannerImage: "/file.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-22",
    capacity: 280,
    seatsRemaining: 60,
    difficultyLevel: "Beginner",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Mind Games Club"],
    location: "Block B Auditorium",
    trendingScore: 67,
    featured: false,
  },
  {
    id: "inverse-coding",
    title: "Inverse Coding",
    organizer: "Problem Solving Desk",
    shortDescription: "Deduce hidden logic from input-output behavior.",
    fullDescription:
      "Round 1 is a quiz-based shortlist on DS, aptitude, C, and algorithms. Round 2 requires participants to infer logic from executable programs and reproduce matching source code behavior.",
    eventDate: "2026-03-10T09:00:00",
    duration: "2h 55m",
    mode: "Offline",
    category: "tech",
    rating: 4.8,
    reviewCount: 133,
    registrations: 310,
    tags: ["Algorithms", "C", "Reverse Logic"],
    thumbnailImage: "/next.svg",
    bannerImage: "/window.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-25",
    capacity: 360,
    seatsRemaining: 50,
    difficultyLevel: "Advanced",
    certificateProvided: true,
    price: "$8",
    sponsors: ["Algo Hub"],
    location: "Programming Lab 1",
    trendingScore: 91,
    featured: true,
  },
  {
    id: "cluedo-live",
    title: "CLUEDO",
    organizer: "Creative Events Team",
    shortDescription: "Live action mystery with clues, suspects, and twists.",
    fullDescription:
      "An immersive offline detective storyline where teams inspect scenes, interrogate suspects, and solve layered clues. The event emphasizes observation, collaboration, and logical deduction in a cinematic game format.",
    eventDate: "2026-03-11T10:00:00",
    duration: "1h 15m",
    mode: "Offline",
    category: "non-tech",
    rating: 4.7,
    reviewCount: 162,
    registrations: 470,
    tags: ["Mystery", "Detective", "Teamwork"],
    thumbnailImage: "/globe.svg",
    bannerImage: "/next.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-25",
    capacity: 520,
    seatsRemaining: 50,
    difficultyLevel: "Intermediate",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Culture Cell"],
    location: "Activity Zone",
    trendingScore: 89,
    featured: true,
  },
  {
    id: "catch-me-if-you-can",
    title: "Catch Me If You Can (QR Hunt)",
    organizer: "Treasure Hunt Squad",
    shortDescription: "QR-based clue hunt with puzzle and campus navigation.",
    fullDescription:
      "Teams solve seven sequential clues by scanning QR codes across campus. Challenges include riddles, ciphers, and domain questions, with ranking based on completion time and hint penalties.",
    eventDate: "2026-03-11T09:30:00",
    duration: "2h",
    mode: "Offline",
    category: "non-tech",
    rating: 4.6,
    reviewCount: 143,
    registrations: 430,
    tags: ["QR Hunt", "Puzzle", "Campus"],
    thumbnailImage: "/vercel.svg",
    bannerImage: "/globe.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-24",
    capacity: 500,
    seatsRemaining: 70,
    difficultyLevel: "Intermediate",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Student Forum"],
    location: "Campus Wide",
    trendingScore: 87,
    featured: true,
  },
  {
    id: "fun-zone",
    title: "FUN ZONE",
    organizer: "Engagement Team",
    shortDescription: "Casual mini-games and ring-throw prize activities.",
    fullDescription:
      "A playful event area with multiple interactive activities including pose matching, headphone chain challenge, and improv responses. Participants can complete sets for ring-throw prize attempts.",
    eventDate: "2026-03-11T11:00:00",
    duration: "2h",
    mode: "Offline",
    category: "non-tech",
    rating: 4.2,
    reviewCount: 69,
    registrations: 280,
    tags: ["Games", "Fun", "Prizes"],
    thumbnailImage: "/file.svg",
    bannerImage: "/window.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-22",
    capacity: 350,
    seatsRemaining: 120,
    difficultyLevel: "Beginner",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Student Union"],
    location: "Open Ground",
    trendingScore: 58,
    featured: false,
  },
  {
    id: "movie-mania",
    title: "MOVIE MANIA",
    organizer: "Fandom Club",
    shortDescription: "Cinema and pop-culture quiz with media-based rounds.",
    fullDescription:
      "Round 1 includes mixed-format movie questions from audio, posters, props, and emoji clues. Qualified teams move to a deeper competitive round on film knowledge with partial scoring for later attempts.",
    eventDate: "2026-03-11T13:00:00",
    duration: "1h 30m",
    mode: "Offline",
    category: "non-tech",
    rating: 4.5,
    reviewCount: 118,
    registrations: 360,
    tags: ["Cinema", "Quiz", "Pop Culture"],
    thumbnailImage: "/window.svg",
    bannerImage: "/file.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-24",
    capacity: 420,
    seatsRemaining: 60,
    difficultyLevel: "Beginner",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Media Cell"],
    location: "Seminar Hall A",
    trendingScore: 77,
    featured: false,
  },
  {
    id: "paper-odyssey",
    title: "Paper Odyssey",
    organizer: "Arts & Craft Club",
    shortDescription: "Theme-based craft creation and replication challenge.",
    fullDescription:
      "Round 1 focuses on original craft creation based on assigned themes. Round 2 tests precision by recreating a reference craft image using limited paper materials and coordinated teamwork.",
    eventDate: "2026-03-11T14:00:00",
    duration: "50m",
    mode: "Offline",
    category: "non-tech",
    rating: 4.1,
    reviewCount: 55,
    registrations: 190,
    tags: ["Craft", "Creativity", "Design"],
    thumbnailImage: "/next.svg",
    bannerImage: "/window.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-21",
    capacity: 240,
    seatsRemaining: 70,
    difficultyLevel: "Beginner",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Creative Studio"],
    location: "Workshop Room 3",
    trendingScore: 52,
    featured: false,
  },
  {
    id: "memory-game",
    title: "Memory Game - Image, Audio & Object Memory",
    organizer: "Cognitive Challenge Desk",
    shortDescription: "Visual, audio, and object-memory recall challenge.",
    fullDescription:
      "Round 1 tests recall from rapid PPT images and audio clips. Round 2 challenges participants to reconstruct object arrangements after brief observation, evaluating detail retention and accuracy.",
    eventDate: "2026-03-11T15:00:00",
    duration: "1h",
    mode: "Offline",
    category: "non-tech",
    rating: 4.4,
    reviewCount: 81,
    registrations: 240,
    tags: ["Memory", "Observation", "Recall"],
    thumbnailImage: "/globe.svg",
    bannerImage: "/vercel.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-23",
    capacity: 300,
    seatsRemaining: 60,
    difficultyLevel: "Intermediate",
    certificateProvided: false,
    price: "Free",
    sponsors: ["Mind Lab"],
    location: "Hall D",
    trendingScore: 73,
    featured: false,
  },
  {
    id: "the-great-escape",
    title: "The Great Escape - Day",
    organizer: "Challenge Room Team",
    shortDescription: "MCQ logic round followed by themed escape challenges.",
    fullDescription:
      "Round 1 includes timed riddles and analytical puzzle MCQs for shortlisting. Round 2 places qualified teams in an on-spot themed challenge where points and completion speed determine winners.",
    eventDate: "2026-03-11T09:30:00",
    duration: "3h 55m",
    mode: "Offline",
    category: "non-tech",
    rating: 4.8,
    reviewCount: 147,
    registrations: 390,
    tags: ["Escape", "Logic", "Team"],
    thumbnailImage: "/vercel.svg",
    bannerImage: "/next.svg",
    version: "2026 Edition",
    lastUpdated: "2026-02-25",
    capacity: 430,
    seatsRemaining: 40,
    difficultyLevel: "Advanced",
    certificateProvided: true,
    price: "$5",
    sponsors: ["Adventure Society"],
    location: "Escape Arena",
    trendingScore: 92,
    featured: true,
  },
];
